<?php

namespace LazyAnts\Bundle\FrontBundle\Repository;
use Doctrine\ORM\NoResultException;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends \Doctrine\ORM\EntityRepository
{

    public function findTeamByName($name)
    {
        try
        {
            $team = $this->findOneBy(array('name' => $name));

            if (is_null($team))
            {
                $team = $this->searchTeamByNamePart(substr($name, 0, -3));
            }
        }
        catch (NoResultException $e)
        {
            return null;
        }

        return $team;

    }

    private function searchTeamByNamePart($search)
    {
        return $this->createQueryBuilder('team')
                    ->where('team.name LIKE :name')
                    ->setParameter('name', '%'. $search .'%')
                    ->getQuery()
                    ->getSingleResult();
    }



}
